/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiClasses;

import oopClasses.EmployeeManagementModule;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import motorphpayroll.customcomponents.CustomPanel;
import motorphpayroll.customcomponents.MyButton;
import motorphpayroll.customcomponents.RoundJTextField;

/**
 *
 * @author keith
 */
public class AddorEditEmployeeGui extends javax.swing.JFrame {

    private boolean isAddingEmployee;
    private int employeeId;
    private EmployeeManagementModule empModule;
    private JTable empTable;
    private String [] details = new String[13];
    private SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
    
    public AddorEditEmployeeGui(boolean isAddingEmployee, int employeeId, JTable empTable) {
        initComponents();
        this.isAddingEmployee = isAddingEmployee;
        this.employeeId = employeeId;
        this.empTable = empTable;
        empModule = new EmployeeManagementModule();
        adjustSearchField();
        identifyUserAction();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new CustomPanel(new Color(213,213,213), new Color(158,158,158));
        titleLabel = new javax.swing.JLabel();
        closeButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        manageEmpLabel1 = new javax.swing.JLabel();
        firstName = new RoundJTextField(5);
        birthday = new RoundJTextField(5);
        phoneNum = new RoundJTextField(5);
        address = new RoundJTextField(5);
        lastName = new RoundJTextField(5);
        jPanel5 = new javax.swing.JPanel();
        manageEmpLabel3 = new javax.swing.JLabel();
        position = new RoundJTextField(5);
        hourlyRate = new RoundJTextField(5);
        jPanel6 = new javax.swing.JPanel();
        manageEmpLabel4 = new javax.swing.JLabel();
        sssNum = new RoundJTextField(5);
        philhealthNum = new RoundJTextField(5);
        pagibigNum = new RoundJTextField(5);
        tinNum = new RoundJTextField(5);
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        saveButton = new MyButton();
        discardButton = new MyButton();
        roleComboBox = new javax.swing.JComboBox<>();
        statusComboBox = new javax.swing.JComboBox<>();
        birthdayChooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(860, 560));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(860, 560));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(853, 60));

        titleLabel.setBackground(new java.awt.Color(47, 36, 56));
        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(47, 36, 56));
        titleLabel.setText("ADD NEW EMPLOYEE");

        closeButton2.setBackground(new java.awt.Color(153, 153, 153));
        closeButton2.setForeground(new java.awt.Color(204, 204, 204));
        closeButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close (1).png"))); // NOI18N
        closeButton2.setBorder(null);
        closeButton2.setBorderPainted(false);
        closeButton2.setContentAreaFilled(false);
        closeButton2.setFocusPainted(false);
        closeButton2.setFocusable(false);
        closeButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(closeButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        manageEmpLabel1.setBackground(new java.awt.Color(47, 36, 56));
        manageEmpLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        manageEmpLabel1.setForeground(new java.awt.Color(47, 36, 56));
        manageEmpLabel1.setText("PERSONAL INFORMATION");

        firstName.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        firstName.setForeground(new java.awt.Color(0, 0, 0));
        firstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstNameKeyTyped(evt);
            }
        });

        birthday.setEditable(false);
        birthday.setBackground(new java.awt.Color(255, 255, 255));
        birthday.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        birthday.setForeground(new java.awt.Color(0, 0, 0));
        birthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdayActionPerformed(evt);
            }
        });
        birthday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                birthdayKeyTyped(evt);
            }
        });

        phoneNum.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        phoneNum.setForeground(new java.awt.Color(0, 0, 0));
        phoneNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNumKeyTyped(evt);
            }
        });

        address.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        address.setForeground(new java.awt.Color(0, 0, 0));

        lastName.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lastName.setForeground(new java.awt.Color(0, 0, 0));
        lastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastNameKeyTyped(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        manageEmpLabel3.setBackground(new java.awt.Color(47, 36, 56));
        manageEmpLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        manageEmpLabel3.setForeground(new java.awt.Color(47, 36, 56));
        manageEmpLabel3.setText("EMPLOYMENT DETAILS");

        position.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        position.setForeground(new java.awt.Color(0, 0, 0));
        position.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                positionKeyTyped(evt);
            }
        });

        hourlyRate.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        hourlyRate.setForeground(new java.awt.Color(0, 0, 0));
        hourlyRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hourlyRateKeyTyped(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        manageEmpLabel4.setBackground(new java.awt.Color(47, 36, 56));
        manageEmpLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        manageEmpLabel4.setForeground(new java.awt.Color(47, 36, 56));
        manageEmpLabel4.setText("GOVERNMENT NUMBERS");

        sssNum.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        sssNum.setForeground(new java.awt.Color(0, 0, 0));
        sssNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sssNumKeyTyped(evt);
            }
        });

        philhealthNum.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        philhealthNum.setForeground(new java.awt.Color(0, 0, 0));
        philhealthNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                philhealthNumKeyTyped(evt);
            }
        });

        pagibigNum.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        pagibigNum.setForeground(new java.awt.Color(0, 0, 0));
        pagibigNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pagibigNumKeyTyped(evt);
            }
        });

        tinNum.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tinNum.setForeground(new java.awt.Color(0, 0, 0));
        tinNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tinNumKeyTyped(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("First Name");

        jLabel43.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("Last Name");

        jLabel44.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Birthday");

        jLabel45.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Phone Number");

        jLabel46.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("Address");

        jLabel47.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("Status");

        jLabel48.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("Position");

        jLabel49.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("Hourly Rate");

        jLabel51.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 0, 0));
        jLabel51.setText("Philhealth Number");

        jLabel52.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 0, 0));
        jLabel52.setText("PAG-IBIG Number");

        jLabel53.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 0, 0));
        jLabel53.setText("TIN Number");

        jLabel54.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(0, 0, 0));
        jLabel54.setText("   SSS Number");

        jLabel50.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("Role");

        saveButton.setBackground(new java.awt.Color(252, 141, 80));
        saveButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Save");
        saveButton.setBorderPainted(false);
        saveButton.setFocusable(false);
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveButtonMouseExited(evt);
            }
        });
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        discardButton.setBackground(new java.awt.Color(215, 43, 43));
        discardButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        discardButton.setForeground(new java.awt.Color(255, 255, 255));
        discardButton.setText("Discard");
        discardButton.setBorderPainted(false);
        discardButton.setFocusable(false);
        discardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                discardButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                discardButtonMouseExited(evt);
            }
        });
        discardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardButtonActionPerformed(evt);
            }
        });

        roleComboBox.setBackground(new java.awt.Color(255, 255, 255));
        roleComboBox.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        roleComboBox.setForeground(new java.awt.Color(0, 0, 0));
        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee", "HR", "Finance", "IT" }));
        roleComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        roleComboBox.setFocusable(false);

        statusComboBox.setBackground(new java.awt.Color(255, 255, 255));
        statusComboBox.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        statusComboBox.setForeground(new java.awt.Color(0, 0, 0));
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Probationary" }));
        statusComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        statusComboBox.setFocusable(false);

        birthdayChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                birthdayChooserPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageEmpLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(manageEmpLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(birthdayChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lastName)
                                        .addComponent(phoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sssNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pagibigNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(159, 159, 159))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(manageEmpLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(philhealthNum, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tinNum, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(discardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(manageEmpLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(manageEmpLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sssNum, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(philhealthNum, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pagibigNum, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tinNum, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(birthdayChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(address, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(manageEmpLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(discardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void setDetails () {
        details[0] = firstName.getText();
        details[1] = lastName.getText();
        details[2] = address.getText();
        details[3] = birthday.getText();
        details[4] = position.getText();
        details[5] = phoneNum.getText();
        details[6] = sssNum.getText();
        details[7] = philhealthNum.getText();
        details[8] = tinNum.getText();
        details[9] = pagibigNum.getText();
        details[10] = statusComboBox.getSelectedItem().toString();
        details[11] = hourlyRate.getText();
        details[12] = roleComboBox.getSelectedItem().toString();
    }
    
    private void populateTextFields () {
        String [] empDetails = empModule.getEmployeeDetails(employeeId);
        
        firstName.setText(empDetails[1].trim());
        lastName.setText(empDetails[2].trim());
        birthday.setText(empDetails[3].trim());
        phoneNum.setText(empDetails[4].trim());
        address.setText(empDetails[5].trim());
        statusComboBox.setSelectedItem(empDetails[6].trim());
        position.setText(empDetails[7].trim());
        hourlyRate.setText(empDetails[8].trim());
        roleComboBox.setSelectedItem(empDetails[9].trim());
        sssNum.setText(empDetails[10].trim());
        philhealthNum.setText(empDetails[11].trim());
        pagibigNum.setText(empDetails[12].trim());
        tinNum.setText(empDetails[13].trim());
    }
         
    public void loadEmployeeTable () {
        List <String []> employeeList = empModule.getAllRecords();
        DefaultTableModel tblmodel = (DefaultTableModel) empTable.getModel();
        tblmodel.setRowCount(0);
        
        for (String [] employeeDetails: employeeList) {
            tblmodel.addRow(new Object [] {employeeDetails[0], employeeDetails[1], employeeDetails[2]} );
        }
    }
    
    private void identifyUserAction () {
        if (!isAddingEmployee) {
            titleLabel.setText("EDIT EMPLOYEE");
            populateTextFields();
        }
    }
    
    private boolean hasLetters (String input) {
        for (char c: input.toCharArray()) {
            if (Character.isLetter(c)) {
                return true;
            }
        }
        return false;
    }
    
    public boolean hasBlankFields (JTextField field1, JTextField field2, JTextField field3, JTextField field4, JTextField field5,
                                   JTextField field6, JTextField field7, JTextField field8, JTextField field9, JTextField field10,
                                   JTextField field11) 
    {
        return field1.getText().isBlank() || field2.getText().isBlank() || field3.getText().isBlank() || field4.getText().isBlank() ||
               field5.getText().isBlank() || field6.getText().isBlank() || field7.getText().isBlank() || field8.getText().isBlank() ||
               field9.getText().isBlank() || field10.getText().isBlank() || field11.getText().isBlank();
    }
    
    private void allowOnlyLetters (KeyEvent evt) {
        char letter = evt.getKeyChar();
        if (!Character.isLetter(letter) && letter != ' ') {
            evt.consume();
        }
    }
    
    private void allowOnlyNumbers (KeyEvent evt) {
        char letter = evt.getKeyChar();
        if (!Character.isDigit(letter) && letter != '-') {
            evt.consume(); // Prevent non-numeric characters
        }
    }
    
    private boolean hasNegatives(JTextField phoneNum, JTextField hourlyRate, JTextField sssNum, 
                             JTextField philhealthNum, JTextField pagibigNum, JTextField tinNum) {
    return phoneNum.getText().trim().startsWith("-") ||
           hourlyRate.getText().trim().startsWith("-") ||
           sssNum.getText().trim().startsWith("-") ||
           philhealthNum.getText().trim().startsWith("-") ||
           pagibigNum.getText().trim().startsWith("-") ||
           tinNum.getText().trim().startsWith("-");
}
    
    private boolean validateInputFields () {
        if (hasNumbers(firstName.getText()) || hasNumbers(lastName.getText()) || hasNumbers(position.getText())) {
            JOptionPane.showMessageDialog(this, 
            "First Name, Last Name, and Position should not contain numbers. Please enter letters only.", 
            "Validation Error", 
            JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if (hasLetters(hourlyRate.getText()) || hasLetters(phoneNum.getText()) || hasLetters(sssNum.getText()) || hasLetters(philhealthNum.getText()) || hasLetters(pagibigNum.getText()) || hasLetters(tinNum.getText())) {
            JOptionPane.showMessageDialog(null, "Only Numerical values are allowed for:\n"
                                              + "- Phone Number\n "
                                              + "- Hourly Rate\n"
                                              + "- Government Numbers");
            return false;
        }
        if (hasBlankFields(firstName, lastName, birthday, phoneNum, address, position, hourlyRate, sssNum, philhealthNum, pagibigNum, tinNum)) {
            JOptionPane.showMessageDialog(null, "Please fill up all information");
            return false;
        }
        if (hasNegatives(phoneNum, hourlyRate, sssNum, philhealthNum, pagibigNum, tinNum)) {
            JOptionPane.showMessageDialog(null, "Negative numbers are not allowed for:\n"
                                              + "- Phone Number\n "
                                              + "- Hourly Rate\n"
                                              + "- Government Numbers");                                              
            return false;
        }
        if (!hourlyRate.getText().matches("^\\d+(\\.\\d{1,2})?$")) {
            JOptionPane.showMessageDialog(null, "Invalid Hourly Rate format: Please enter a valid number with up to two decimal places.");
            return false;
        }
        
        Date selectedDate = birthdayChooser.getDate();
        Date currentDate = new Date();
        if (selectedDate != null && selectedDate.after(currentDate)) {            
            JOptionPane.showMessageDialog(null, "Birthdate cannot be in the future");
            return false;
        }
        if (selectedDate != null && calculateAge(selectedDate) < 18) {            
            JOptionPane.showMessageDialog(null, "Employee must be at least 18 years old.");
            return false;
        }
        if (!isValidPhoneNumber(phoneNum.getText())) {
            JOptionPane.showMessageDialog(null, "Invalid phone number format. Format must be: XXX-XXX-XXX");
            return false;
        }
        if (!isValidSSSNumber(sssNum.getText())) {
            JOptionPane.showMessageDialog(null, "Invalid SSS number format. Format must be: XX-XXXXXXX-X");
            return false;
        }
        if (!isValidPagibigOrPhilhealthNumber(pagibigNum.getText())) {
            JOptionPane.showMessageDialog(null, "Invalid Pagibig/Philhealth number format. Must consist of 12 digits");
            return false;
        }
        if (!isValidPagibigOrPhilhealthNumber(philhealthNum.getText())) {
            JOptionPane.showMessageDialog(null, "Invalid Pagibig/Philhealth number format. Must consist of 12 digits");
            return false;
        }
        if (!isValidTIN(tinNum.getText())) {
            JOptionPane.showMessageDialog(null, "Invalid TIN number format. Format must be ###-###-###-###");
            return false;
        }
        if (hasSpecialCharacters(firstName.getText()) || hasSpecialCharacters(lastName.getText()) || hasSpecialCharacters(position.getText())) {
            JOptionPane.showMessageDialog(this, "Special characters are not allowed for \n - First Name \n - Last Name \n - Position");
            return false;
        }
        
        
        return true;
    }
    
    
    public boolean isValidPhoneNumber(String phoneNumber) {
        return phoneNumber.matches("\\d{3}-\\d{3}-\\d{3}");
    }
    
    public boolean isValidSSSNumber(String sssNumber) {
        return sssNumber.matches("\\d{2}-\\d{7}-\\d{1}");
    }
    public boolean isValidPagibigOrPhilhealthNumber(String pagibigNumber) {
        return pagibigNumber.matches("\\d{12}");
    }   
    public boolean isValidTIN(String tin) {
        return tin.matches("\\d{3}-\\d{3}-\\d{3}-\\d{3}");
    }   
    
    public boolean hasNumbers(String input) {
        return input.matches(".*\\d+.*");
    }
    
    public boolean hasSpecialCharacters (String input) {
        String regex = "[^a-zA-Z0-9 ]";  
        return input.matches(".*" + regex + ".*");
    }
        
    private void closeButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButton2ActionPerformed
    
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (!validateInputFields()) {
            return;
        }
        
        setDetails();
        if (isAddingEmployee) {           
            boolean added = empModule.addEmployee(details);
            if (added){
                JOptionPane.showMessageDialog(null, "Record Added Sucessfully");
            } 
            else {
                JOptionPane.showMessageDialog(null, "Failed to add record");
            }
                      
        }
        else {
            boolean edited = empModule.editEmployee(employeeId, details);
            if (edited) {
                JOptionPane.showMessageDialog(null, "Record Updated Sucessfully");
            }
            else {
                JOptionPane.showMessageDialog(null, "Failed to update record");
            }
        }
        loadEmployeeTable();
        this.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void discardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_discardButtonActionPerformed

    private void firstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameKeyTyped
        allowOnlyLetters(evt);
    }//GEN-LAST:event_firstNameKeyTyped

    private void lastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameKeyTyped
        allowOnlyLetters(evt);
    }//GEN-LAST:event_lastNameKeyTyped

    private void positionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_positionKeyTyped
        allowOnlyLetters(evt);
    }//GEN-LAST:event_positionKeyTyped

    private void sssNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sssNumKeyTyped
        allowOnlyNumbers(evt);
    }//GEN-LAST:event_sssNumKeyTyped

    private void philhealthNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_philhealthNumKeyTyped
        allowOnlyNumbers(evt);
    }//GEN-LAST:event_philhealthNumKeyTyped

    private void pagibigNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pagibigNumKeyTyped
        allowOnlyNumbers(evt);
    }//GEN-LAST:event_pagibigNumKeyTyped

    private void tinNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tinNumKeyTyped
        allowOnlyNumbers(evt);
    }//GEN-LAST:event_tinNumKeyTyped

    private void hourlyRateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hourlyRateKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '.') {
            evt.consume(); // Prevent non-numeric characters
        }
    }//GEN-LAST:event_hourlyRateKeyTyped

    private void phoneNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumKeyTyped
        allowOnlyNumbers(evt);
    }//GEN-LAST:event_phoneNumKeyTyped

    private void birthdayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_birthdayKeyTyped
        char letter = evt.getKeyChar();
        if (!Character.isDigit(letter) ) {
            evt.consume(); // Prevent non-numeric characters
        }
    }//GEN-LAST:event_birthdayKeyTyped

    private void discardButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_discardButtonMouseEntered
        discardButton.setBackground(new Color(221,74,74));
    }//GEN-LAST:event_discardButtonMouseEntered

    private void discardButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_discardButtonMouseExited
        discardButton.setBackground(new Color(215,43,43));
    }//GEN-LAST:event_discardButtonMouseExited

    private void saveButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseEntered
        saveButton.setBackground(new Color(255,165,115));
    }//GEN-LAST:event_saveButtonMouseEntered

    private void saveButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseExited
        saveButton.setBackground(new Color(252,141,80));
    }//GEN-LAST:event_saveButtonMouseExited

    private void birthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdayActionPerformed
    
    public static int calculateAge(Date birthDate) {
        long ageInMillis = new Date().getTime() - birthDate.getTime();
        return (int) (ageInMillis / (1000L * 60 * 60 * 24 * 365)); // Convert to years
    }
    
    private void birthdayChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_birthdayChooserPropertyChange
        if (birthdayChooser.getDate() == null) return;       
        birthday.setText(dateFormat.format(birthdayChooser.getDate()));
        System.out.println(dateFormat.format(birthdayChooser.getDate()));
    }//GEN-LAST:event_birthdayChooserPropertyChange

   private void adjustSearchField() {
        firstName.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(firstName.getForeground(), 1),
                    new EmptyBorder(5, 10, 5, 10)
            ));
        lastName.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(lastName.getForeground(), 1),
                    new EmptyBorder(5, 10, 5, 10)
            ));
        birthday.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(birthday.getForeground(), 1),
                    new EmptyBorder(5, 10, 5, 10)
            ));
        phoneNum.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(phoneNum.getForeground(), 1),
                    new EmptyBorder(5, 10, 5, 10)
            ));
        address.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(address.getForeground(), 1),
                    new EmptyBorder(5, 10, 5, 10)
            ));
      
        position.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(position.getForeground(), 1),
                    new EmptyBorder(5, 10, 5, 10)
            ));
        hourlyRate.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(hourlyRate.getForeground(), 1),
                    new EmptyBorder(5, 10, 5, 10)
            ));
       
        sssNum.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(sssNum.getForeground(), 1),
                    new EmptyBorder(5, 10, 5, 10)
            ));
        philhealthNum.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(philhealthNum.getForeground(), 1),
                    new EmptyBorder(5, 10, 5, 10)
            ));
        pagibigNum.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(pagibigNum.getForeground(), 1),
                    new EmptyBorder(5, 10, 5, 10)
            ));
        tinNum.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(tinNum.getForeground(), 1),
                    new EmptyBorder(5, 10, 5, 10)
            ));
        
        
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField birthday;
    private com.toedter.calendar.JDateChooser birthdayChooser;
    private javax.swing.JButton closeButton2;
    private javax.swing.JButton discardButton;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField hourlyRate;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField lastName;
    private javax.swing.JLabel manageEmpLabel1;
    private javax.swing.JLabel manageEmpLabel3;
    private javax.swing.JLabel manageEmpLabel4;
    private javax.swing.JTextField pagibigNum;
    private javax.swing.JTextField philhealthNum;
    private javax.swing.JTextField phoneNum;
    private javax.swing.JTextField position;
    private javax.swing.JComboBox<String> roleComboBox;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField sssNum;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JTextField tinNum;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
